apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clara-ingress
  labels:
    app: clara
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: clara.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: clara
            port:
              number: 6060

