---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clara-secrets
  namespace: clara
spec:
  encryptedData:
    google-api-key: AgBGru8xzIIa3KV2wF81rWeB9GU4QOp4ZD2sIGFmBYuWcmTDfdOwud0JzRYrRCrYZ/83pVYry4rRutUEqKY+pQDOZuxvQn+JW4882xva/ET7buY6K7EmPMbAqfrG47jKLzLxsw43rf97Y7XJ0ZsJbZpwB6DryMcMeS+T574Id2EkxnPCghxeea3SmhPpLxk1UiQ1v47QPph5FSt+ti+4RWk/aUG7PSOWiLu9GF4lD2DNeOeKIsZtKTLzIoRf2v8cAQyKgPWR7vYkLoDtlPgoaciPwe9w7Ps2QjlAEgG3IGt9TkCYI6HrBT8Uw8EDvuT2JJORGWEXHxAKeZ/ZK4Bl4iayHyM2QK64PUMrVgMrThLtitrmIazAO+gNTUJfEZUxBU3vrRHufwQUqLXX/HqMRN7MnXQ7iANSd2/roPqfLzKCm4aEm2rqxPNl/h4cFN1TCOi8nT2njhp8MQZMP2kac+1H/KcBsjKuWqMke01LPQq3sGL1t3O60E5fjwNOdRiqvx2WlIA2RZ8FF5G1XH3T/LfY+tKCMVy4eWC7keAof5kvqCUTW3qRWN40l785/mAJ3VNJM7iiHrPxIzBnjbsREDjp+zhwvQDCvlIrlS/DKc5FSTH9TvLAtPBQ+beDVk3+KbUWZw8jXpkb4lN8DQWP508SZpyUmIRTIL2JUwgOXUJVvYB0wMlvGx/vl0uX1Z+BtG8ytiLTtv0pbnr5582GWZDEA0PCxcFeTgESBXhHVtSdZsH6A8Fxqjw=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: clara
      name: clara-secrets
      namespace: clara
    type: Opaque
