---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clara-secrets
  namespace: clara
spec:
  encryptedData:
    google-api-key: AgCOAXIIYAtDNvIqEPq6BtoUZYOEnrYhgK+iiIoFzeidigbIk1ihpv97AWO4Xeyo2HlZVxW4/7pHrOu7IUy5+fVQY+MPBKKMRvDs7p0h1QC1q8gBrFQREdJKElRXuw6dF0c5HQoB9x5WynwquCfPm1hVsBNszTxuxaQVPFnDWJfdA8p4qbE4wkToPXApPtXO/QekJU0tNdfDZPOtkEJHzeugoBydIlnp2grwkOVHyABw7NMrEG6Bv3wWWg379/C1MU04UtFJts/3JljuQTGF/OUQ2HfedbLmdwTfMKQZ3jsXGt0pREr/7KqpEtQYtYlnHb1HlIOkNXWMaTW2qY+dk4+5zJfEUvPUMihHKZNhJUweNldNqrsPiXfB1pAtBWGfO98DAvEh8UG6+lDb76ZO49wlaOOpVeLFNvvFmzqM6KhkcHGH1NJLUjEyy23jubymSPRtW1UGYTP+kn+TAAN/uNt/kxsS6THN/G320YxDl8et1MnaOpjpHLtvFijFOwell3CvFaaL+ZJ5o5zk5KZOwfhQvdfU0cNSk4E6l5Jh0TjCHfMD4+MGkIMyLUhUdzAv1852950bTA7zDTYHi/IyBHmwd7oHZgqnEeJydCBLKtO0TSF51guxq0VKHkfHantMgINP4L3oUiEeneylh8Rvq6e5SwRn8NBSvi0vIDdnygKqSfdK8dh6/I6nVc/toJFegC7LTnlYMLpdD3DU/KS9ve6BHvwIKe86Cg36w+tkjLS8H79nXsTiHUk=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: clara
      name: clara-secrets
      namespace: clara
    type: Opaque
