apiVersion: v1
kind: Service
metadata:
  name: clara
  labels:
    app: clara
    app.kubernetes.io/name: clara
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 6060
    targetPort: 6060
    protocol: TCP
  selector:
    app: clara

